name: E2E Tests

on: pull_request

jobs:
  test:
    runs-on: ubuntu-16.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Waiting for 200 from the Netlify Preview
        uses: jakepartusch/wait-for-netlify-action@v1.2
        id: waitFor200
        with:
          site_name: "openpracticelibrary"
          max_timeout: 3600

      - name: Cypress Tests
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          config: baseUrl=${{ steps.waitForDeployment.outputs.url }}
          record: true
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # this is automatically set by GitHub
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}